plugins:
  - babel
env:
  node: true
parser: babel-eslint
extends:
  - 'airbnb-base'
rules:
  no-console: 0
  arrow-parens: 0
  implicit-arrow-linebreak: 0
  function-paren-newline: 0
  eslint-disable operator-linebreak: 0
  no-restricted-syntax: 0
  no-await-in-loop: 0
  operator-linebreak: 0
